### PR TITLE
Support vite 2.7 and later

### PR DESCRIPTION
**Pull request by medmunds**
Plugin API changed in vite 2.7.0 [1].

[1]: https://github.com/vitejs/vite/blob/main/packages/vite/CHANGELOG.md#270-2021-12-07

### CODE REVIEW

**Comment by sync** [comment]
thank you, will merge now

**Comment by medmunds** [comment]
@sync thanks. Would it be a lot of trouble to publish an updated package? (If it's a hassle, I'm fine installing direct-from-git. Just FYI, this package comes up as the only current solution for getting vite HMR working with Lit v2/lit-html.)

**Comment by sync** [comment]
No happy to do it, once back at my computer

**Comment by cuberoot** [comment]
Did the release ever happen? I just installed today and it looks like I don't have the patch.

**Comment by sync** [comment]
nope, not actively maintaining this anymore sorry I forgot

**Pull request merged**
